### ISSUE TITLE
Yum repo URL has changed

### ISSUE THREAD

**Issue by joseofarrill-work** [queeno/ansible-uchiwa#2]
the repo files fail on AWS Linux (Redhat family)

Old repo 
baseurl=http://repos.sensuapp.org/yum/el/$releasever/$basearch/
New repo
baseurl=http://repos.sensuapp.org/yum/el/$basearch/

from https://sensuapp.org/docs/0.20/install-repositories

**Comment by queeno** [comment]
Thanks very much @joseofarrill-work for reporting this bug.

I will write a patch very soon. Stay tuned!

**Comment by queeno** [comment]
Hi @joseofarrill-work 

I have tested the old repo in the bento/centos-7.1 vagrant box, where this role works just fine. You can do the same by running `vagrant up redhat` in the top level folder of this repo.

I have also replicated your error using the AWS free tier AMI. I've realised that the `$releasever` built-in YUM variable is set to `latest`, as indicated by the `/etc/yum.conf` file:

```
# by default the yum configuration will point to the latest release
# of Amazon Linux AMI. If you prefer not to automatically move to
# new releases, comment out this line.
releasever=latest
```

When commented out, `releasever` defaults to the appropriate version of RedHat linux. This is why the 'old repo url' works just fine in vagrant (and on all the non-AWS builds).

Now, the sensu yum repo doesn't support `releasever=latest` and - as you've pointed out - the sensu documentation suggests they're not building OS version-specific packages. However, if you hit [http://repos.sensuapp.org](http://repos.sensuapp.org), it seems there are indeed OS version repos (legacy?).

This got me quite confused. For this reason, I will request clarification from the sensu folks.

**Comment by queeno** [comment]
I have opened sensu/sensu#1062 requesting clarification.

**Comment by queeno** [comment]
Hi @joseofarrill-work 

Sensu got back to me on sensu/sensu#1062. They have moved and consolidated the repositories: https://sensuapp.org/docs/latest/install-repositories

I have just pushed a patch to ansible-uchiwa to support the new repositories, both for Debian and RedHat.

Please feel free to reopen this issue in case you have further issues :)
